# Generated by Django 4.2.3 on 2023-09-27 18:40

from django.db import migrations, models
import news.validators.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[news.validators.validators.validator_words],
            ),
        ),
    ]
